version: '3.8'

services:
  frontend:
    build: .
    container_name: gsb_frontend_container
    ports:
      - "5173:5173"
    volumes:
      - .:/app  # Mount local project folder into the container
      - /app/node_modules  # Prevent overwriting node_modules
    environment:
      - VITE_BACKEND_URL=http://backend:8080/api  # Use 'backend' instead of 'localhost'
    command: ["npm", "run", "dev"]
    networks:
      - gsb_shared_network  # Attach service to the network
    depends_on:
      - backend #Ensure the backend starst firts

networks:
  gsb_shared_network:
    external: true
