version: '3.8'

services:
  frontend:
    build: .
    container_name: gsb_frontend
    ports:
      - "80:80"
    environment:
      - VITE_BACKEND_URL=http://localhost:8080/api
    networks:
      - gsb-network

networks:
  gsb-network:
    driver: bridge
