version: '3.8'

services:
  frontend:
    build: .
    container_name: gsb_frontend_container
    ports:
      - "5173:5173"
    volumes:
      - .:/app  # Mount local project folder into the container
      - /app/node_modules  # Prevent overwriting node_modules
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev"]
    networks:
      - gsb-network  # Attach service to the network

networks:
  gsb-network:
    driver: bridge
